In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5],
              [2, 1, 3, 4, 5],
              [2, 5, 6, 7, 1],
              [1, 5, 3, 2, 4]])

In [13]:
np.round([0.03, 0.5111])

array([0., 1.])

In [10]:
np.ceil([0.5])

array([1.])

In [6]:
a.mean(axis=0)

array([1.5 , 3.25, 3.75, 4.25, 3.75])